SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, MAX(RI.FAVORITES) AS FAVORITES
FROM REST_INFO RI INNER JOIN (
        SELECT REST_ID, REST_NAME, MAX(FAVORITES) FAVORITES
        FROM REST_INFO
        GROUP BY FOOD_TYPE) RISQ
    ON RI.FAVORITES = RISQ.FAVORITES
GROUP BY RI.FOOD_TYPE
ORDER BY RI.FOOD_TYPE DESC