SELECT FP.CATEGORY, FP.PRICE MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP INNER JOIN (
        SELECT PRODUCT_ID, MAX(PRICE) PRICE
        FROM FOOD_PRODUCT
        WHERE CATEGORY LIKE "과자" OR CATEGORY LIKE "국" OR CATEGORY LIKE "김치" OR CATEGORY LIKE "식용유"
        GROUP BY CATEGORY) FPSQ
    ON FP.PRICE = FPSQ.PRICE
WHERE CATEGORY LIKE "과자" OR CATEGORY LIKE "국" OR CATEGORY LIKE "김치" OR CATEGORY LIKE "식용유"
ORDER BY FP.PRICE DESC;